version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ro.ot+
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: u.ser+
    networks:
      - wordpress

  wordpress:
    build: docker/apache
    container_name: apache
    volumes: 
      - .:/var/www/html/
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - wordpress

volumes:
    mysql_data:

networks:
    wordpress:

